export const curiosities: string[] = [
    'A palavra "quiz" surgiu em Dublin no século XVIII.',
    'O inglês tem mais de 170.000 palavras atualmente em uso.',
    'A palavra "set" tem mais de 430 significados diferentes no inglês.',
    'O verbo "to run" tem mais de 600 formas diferentes.',
    'O inglês é a terceira língua mais falada no mundo, depois do mandarim e do espanhol.',
    'A letra "e" é a letra mais usada na língua inglesa.',
    'O inglês é uma língua germânica, mas tem muitas influências do latim e do francês.',
    'A palavra "goodbye" vem da expressão "God be with ye".',
    'O inglês é a língua oficial da aviação internacional.',
    'A palavra "alphabet" vem das primeiras duas letras do alfabeto grego: alpha e beta.',
    'O verbo "to be" é o verbo mais irregular em inglês.',
    'A palavra "salary" vem do latim "salarium", que significa "pagamento em sal".',
    'O inglês é a língua mais estudada como segunda língua no mundo.',
    'A palavra "nightmare" originalmente significava um espírito que causava pesadelos.',
    'O inglês tem mais de 1.000 phrasal verbs (verbos frasais).',
    'A palavra "good" tem mais de 20 sinônimos em inglês.',
    'O inglês é a língua oficial das Nações Unidas e da União Europeia.',
    'A palavra "hello" foi popularizada com a invenção do telefone por Alexander Graham Bell.',
    'O inglês é a língua mais usada na internet.',
    'A palavra "friend" vem do antigo inglês "freond", que significa "amigo" ou "amante".',
    'O inglês é a língua oficial do comércio internacional.',
    'A palavra "window" vem do nórdico antigo "vindauga", que significa "olho do vento".',
    'O inglês tem mais de 25 tempos verbais diferentes.',
    'A palavra "goodbye" foi usada pela primeira vez no século XVI.',
    'O inglês é a língua oficial do turismo em muitos países.',
    'A palavra "book" vem do antigo inglês "boc", que significa "livro" ou "documento".',
    'O inglês é a língua oficial do esporte internacional, incluindo os Jogos Olímpicos.',
    'A palavra "school" vem do grego "scholē", que significa "lazer" ou "tempo livre".',
    'O inglês é a língua oficial da ciência e da tecnologia.',
    'A palavra "music" vem do grego "mousikē", que significa "arte das musas".',
    'O inglês é a língua oficial da aviação comercial.',
    'A palavra "computer" foi usada pela primeira vez em 1613 para descrever uma pessoa que fazia cálculos.',
    'O inglês é a língua oficial do cinema e da televisão.',
    'Existem mais de 1.500 dialetos diferentes do inglês ao redor do mundo.',
    'A palavra "breakfast" significa "quebrar o jejum".',
    'Existem mais de 3.000 palavras de origem francesa no inglês.',
    'A palavra "goodnight" é uma combinação de "good" e "night".',
    'O tempo verbal "present perfect" não existe em muitas outras línguas.',
    'A palavra "holiday" vem do inglês antigo "haligdaeg", que significa "dia sagrado".',
    'A palavra mais longa na língua inglesa é "pneumonoultramicroscopicsilicovolcanoconiosis" (uma doença pulmonar).',
    'O inglês é a língua oficial do comércio marítimo internacional.',
    'A menor palavra em inglês é "I" (eu).',
    'A palavra "goodbye" tem várias formas em diferentes dialetos do inglês, como "bye", "see you", "take care"',
    'Não existe uma palavra em inglês que rime com "orange".',
    'A palavra "alphabet" vem do grego antigo, onde "alpha" e "beta" são as duas primeiras letras do alfabeto',
    'O inglês é a língua oficial do turismo em muitos países.',
    'Os Estados Unidos não têm uma língua oficial a nível federal, mas o inglês é a língua predominante.',
    'As cores "blue" e "green" eram originalmente a mesma palavra em inglês antigo: "blǣwen".',
    'Existem mais de 170.000 palavras em uso no inglês moderno, mas uma pessoa média usa apenas cerca de 20.000 a 35.000 palavras no dia a dia.',
    'A palavra "goodbye" foi usada pela primeira vez no século XVI como uma contração de "God be with ye".',
    'A palavra "quiz" foi supostamente inventada em 1791 por um empresário irlandês que fez uma aposta de que poderia introduzir uma nova palavra na língua inglesa em 24 horas.',
    'A palavra "set" tem o maior número de significados diferentes em inglês, com mais de 430 sentidos listados no Oxford English Dictionary.',
    'A palavra "bookkeeper" (contador) é a única palavra em inglês que tem três pares consecutivos de letras repetidas (oo, kk, ee).',
    'A palavra "strengths" é a palavra mais longa em inglês com apenas uma vogal.',
    'A palavra "facetious" contém todas as vogais em ordem alfabética.',
    'A palavra "uncopyrightable" é a palavra mais longa em inglês que não repete nenhuma letra.',
    'A palavra "rhythm" é a palavra mais longa em inglês sem vogais.',
    'A palavra "lollipop" foi originalmente usada para descrever um tipo de chiclete antes de se referir ao doce em um palito.',
    'A palavra "good" tem mais de 20 sinônimos em inglês, incluindo "excellent", "great", "fantastic", "superb", "wonderful", "splendid", "marvelous", "terrific", "fabulous", "outstanding", "brilliant", "amazing", "incredible", "phenomenal", "exceptional", "magnificent", "first-rate", "top-notch", "stellar" e "ace".',
    'A palavra "hello" foi popularizada com a invenção do telefone por Alexander Graham Bell, que inicialmente sugeriu o uso de "ahoy" como saudação ao atender o telefone.',
  
    
  ];