export const TRADUCOES_MOCK: { [key: string]: string } = {
  paradigm: 'paradigma',
  ubiquitous: 'ubíquo(a), presente em todos os lugares',
  intricate: 'intricado(a), complexo(a)',
  ambiguous: 'ambíguo(a), com múltiplos significados',
  facilitate: 'facilitar, promover',
  implement: 'implementar, executar',
  curriculum: 'currículo escolar',
  assessment: 'avaliação',
  proficiency: 'proficiência',
  interdisciplinary: 'interdisciplinar',
  collaboration: 'colaboração',
  engagement: 'engajamento',
  reflective: 'reflexivo(a)',
  paradigm_shift: 'mudança de paradigma',
  scaffolding: 'suporte pedagógico',
  literacy: 'alfabetização',
  methodology: 'metodologia',
  evaluation: 'avaliação',
  feedback: 'retroalimentação',
  cognitive: 'cognitivo(a)',
  autonomy: 'autonomia',
  empathy: 'empatia',
  resilience: 'resiliência',
  innovation: 'inovação',
  competence: 'competência',
  analytical: 'analítico(a)',
  synthesis: 'síntese',
  deduction: 'dedução',
  inference: 'inferência',
  curriculum_design: 'planejamento curricular',
  experiential: 'experiencial',
  pedagogical: 'pedagógico(a)',
  formative: 'formativo(a)',
  summative: 'somativo(a)',
  differentiated: 'diferenciado(a)',
  inclusivity: 'inclusividade',
  motivation: 'motivação',
  metacognition: 'metacognição',
  creativity: 'criatividade',
  critical_thinking: 'pensamento crítico'
};

export const PALAVRAS_SUGERIDAS = Object.keys(TRADUCOES_MOCK);
